### ISSUE TITLE
web_connectivity: allow to visit anomalous URL

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#100]
User story: I am a user, I see that a site is an anomaly, I really can't believe it, and I want to see for myself whether that site is actually blocked, by opening it in the browser, and perhaps after that I may also want to provide some sort of feedback to the app developers.

xref: https://github.com/TheTorProject/ooniprobe-android/issues/70

**Comment by lorenzoPrimi** [comment]
Fixed in the 2.0 app, now you can click an URL in the test result screen
