### ISSUE TITLE
Unclear how to get test methodology information

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#101]
User story: I am an advanced user, I end up in the Run Tests section where I am clearly hinted to hit the Run button to start tests, then I am hinted to go into the Past Tests section, where I can see results; at this point, I see anomalies that I think should not be anomalies, and I don't have a quick way to see the test methodology from the results (not to mention that it's not obvious to me that I can get info on a specific test by going on the Run Tests section and running it).

(IMHO this history seems to suggest that the place where one may want to know about the methodology is indeed when he/she is looking at results, no?)

xref: https://github.com/TheTorProject/ooniprobe-android/issues/71

**Comment by lorenzoPrimi** [comment]
@bassosimone  I guess this can be closed as it's refered to 1.x app

**Comment by hellais** [comment]
I think the user story is still relevant and something to keep in mind when designing the copy for the test details page in the 2.x app.

**Comment by lorenzoPrimi** [comment]
Moved to https://github.com/ooni/probe/issues/822
