### ISSUE TITLE
Test a random sample of URLs from all 31 categories (included in Citizen Lab repo)

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe-ios#104]
Currently ooniprobe's mobile app tests a random sample of URLs from the Citizen Lab's global test list every time the user runs Web Connectivity. This means that, in some cases, users might only be testing pornographic sites (or other sites that might be of less interest to them), instead of testing "more interesting" sites (such as news media, human rights sites, etc.).

A quick fix to this problem could be re-configuring the web connectivity test to test a random sample of URLs that are fetched from all 31 categories (https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv). That way, a user tests a little bit of everything every time he/she runs web connectivity.

**Comment by bassosimone** [comment]
I believe this should be fixed as part of measurement-kit. To actually have this fixed, the specific bit of work to be done is to finish off downloading resources and keeping them up to date. At this point, there will be support for country specific test lists and, thus, sampling will occur including not only the global test list but also the country specific test list. @agrabeli, would this be enough?

**Comment by lorenzoPrimi** [comment]
I guess we can consider this more than done!
