### ISSUE TITLE
Add support for end to end testing

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#121]
As the complexity of the apps increases, so does the likelyhood of introducing defects or possibly regress bugs.

We should come up with a way of doing proper end to end testing and maybe even using something like [Device Farm](https://aws.amazon.com/device-farm) to test the app on real devices.

It seems like one popular choice for this is [Appium](http://appium.io/). I recall looking at it some time ago and it seems OK. I haven't used it though.

An extra bonus we would get from doing this, is that we would have mapped out all the possible states and view for the app that could then be used by designers to check how the app looks in all possible states.

It seems like it's even possible to automatically [take screenshots via appium](http://discuss.appium.io/t/how-to-capture-screenshot/15168/3).

**Comment by hellais** [comment]
I have added a basic set of end to end tests in this branch: https://github.com/ooni/probe-ios/pull/195.

I ended up using the standard iOS testing system and integrated it with fastlane to take screenshots automatically.

**Comment by bassosimone** [comment]
@hellais great work, thanks! 👍
