### ISSUE TITLE
Reindent the code with clang-format

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#124]
Some parts have very long lines and this is making review more complex.

**Comment by lorenzoPrimi** [comment]
@bassosimone do you have a tool to check if there are any or automatically fix these long lines?

**Comment by bassosimone** [comment]
I was suggesting to use clang-format

**Comment by lorenzoPrimi** [comment]
gonna try this https://github.com/travisjeffery/ClangFormat-Xcode or this https://github.com/mapbox/XcodeClangFormat

**Comment by lorenzoPrimi** [comment]
I tried to refactor a few classes with clang, sorry not my style at all, I can't read my code anymore.

I will try to cut long lines manually while keeping the automatic style and indentation used by XCode
