### ISSUE TITLE
Add support for measuring data usage

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#157]
Support already in MK. The app should be updated to use it.

**Comment by meredithpage70** [comment]
This file contains the PGP keys of various developers.

Users: pgp < KEYS
       gpg --import KEYS
Developers:
        pgp -kxa <your name> and append it to this file.
        (pgpk -ll <your name> && pgpk -xa <your name>) >> this file.
        (gpg --list-sigs <your name>
             && gpg --armor --export <your name>) >> this file.


pub   1024D/11A1AE9C 2006-10-19
uid                  Marc Prud'hommeaux (CODE SIGNING KEY) <mprudhom@apache.org>
sig 3        11A1AE9C 2006-10-19  Marc Prud'hommeaux (CODE SIGNING KEY) <mprudhom@apache.org>
sub   2048g/4AA825C2 2006-10-19
sig          11A1AE9C 2006-10-19  Marc Prud'hommeaux (CODE SIGNING KEY) <mprudhom@apache.org>

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.2.2 (Darwin)

mQGiBEU3/c0RBACKG8V5yDWw/9D2EB5zfhy94lEYu2tsp+qjcC5h+DRPr8Clkfht
jWpHRcWmw8gxyYYo6fc8fH9vLljUvEQXmIHU88Qw6XUhGTsKFLsRT1rsN25+6KZG
kH2gnnZUXK1+NSGbiNwlbrgpNHP30JjLH9ewX867hhp24PJ0ke+nlzScBwCgrxsc
kmPXMyFrbbPYMaFO5MfT/R0D/R3o5lhV7mbu2jxKUMfngJYv7uT+IZ8lyquKdIcX
kvwKKqmdPgSJQ9RhJeUYgAlKcZbQst7g2g+XktuotxwNdUdyTGKJA1ieZK7l89U/
zNvQuCnZ9vSzirKydpRVd+ReMupVYooC12GYOl9gLCJg1WQXYdjoKaKF7u1PUsRp
We3XA/9YRNq7alUTRTiS0LY1RfaQohprsLsF+pY+ZkB3A72CZWyWoxQG0uHL3ivq
mGlGYKriKTed4DBRp2ZREsGwbWAknh/wP4Is42qH1RzWRB7xnQsrxYuPFSr4c35D
AP9oFk2O4povTJ9Ay0QEnNRgncIoSuhEXQ0GRLETosmozqBOkLQ7TWFyYyBQcnVk
J2hvbW1lYXV4IChDT0RFIFNJR05JTkcgS0VZKSA8bXBydWRob21AYXBhY2hlLm9y
Zz6IYAQTEQIAIAUCRTf9zQIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEPeU
CvQRoa6ckGAAn131QtlLKvPdUh9NWYwgAsvN8FuSAJ9+8PTwxc4G4NhyNhYV0TcI
2kuANrkCDQRFN/3gEAgAmyDZTIcdHNN76dLsEA9tj+chVf2iDBFisrpmYMV4CM0R
tUD6GYhUDekKWaAs9PnTnqe+9b30NIEmORY6XktWD08GFwwp5loxlLuQlK66I29u
y1dS6J6HdxcFWJlg4v1AnKdHexUSHUbxNrZQtU+N3kAMhsopZhV3QwSK6djMb2Lo
SsNaSmpS+3L9siP8XwkxsPixOfXDTbKtFvb6p0idvetKPrulJnX+zJGupYa4KpkE
G7CpiWgcSFlGU/AVv4xfIqFUX3EwoQefIX/Nw+mlz2fZD0GCfosgLlA2x3gol2ks
77SgzzgH9acNF7xUoJTXHRZdz3Ue2CU2YSvCVBwV9wAFEQf+IXKZVdyjp+vAXSD2
lZHDzRlcI97dnAlsQYVmQOdDJf+haC8KBvZwSEdsCB4Ng6P1aX0xDh2gXxAUzEzJ
sjw4u7QvjKsx44SpC3wXsbJJdzwkM9nyneWul3DyyJ03YB0ReIuP/N5PZHLAKSIG
/n29AK16TJI+ePJtBfMhsjmaHvTjcEHALhG5eN1AtmCKMX60lSu9KYJK01gaiWgb
0lo9MyH4S7TqQHOqSUxF20Q/0fsN3ckkkelVy72vfB3lSbzQyZLrVCwqg10rjxQg
yjHi+tXM8R/gJaP5zRf5v1X0/kjAI2zo99l7eox4mgdfvpOojSBYJMn+097UVHW+
n0/ldohJBBgRAgAJBQJFN/3gAhsMAAoJEPeUCvQRoa6cu8oAoKzP/7i+YnyHHIpW
bZySWmV5ruNBAKCRPW44mWffxSsJ6oUeUSzvbsCwew==
=XKWe

**Comment by meredithpage70** [comment]
This file contains the PGP keys of various developers.

Users: pgp < KEYS
       gpg --import KEYS
Developers:
        pgp -kxa <your name> and append it to this file.
        (pgpk -ll <your name> && pgpk -xa <your name>) >> this file.
        (gpg --list-sigs <your name>
             && gpg --armor --export <your name>) >> this file.


pub   1024D/11A1AE9C 2006-10-19
uid                  Marc Prud'hommeaux (CODE SIGNING KEY) <mprudhom@apache.org>
sig 3        11A1AE9C 2006-10-19  Marc Prud'hommeaux (CODE SIGNING KEY) <mprudhom@apache.org>
sub   2048g/4AA825C2 2006-10-19
sig          11A1AE9C 2006-10-19  Marc Prud'hommeaux (CODE SIGNING KEY) <mprudhom@apache.org>

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.2.2 (Darwin)

mQGiBEU3/c0RBACKG8V5yDWw/9D2EB5zfhy94lEYu2tsp+qjcC5h+DRPr8Clkfht
jWpHRcWmw8gxyYYo6fc8fH9vLljUvEQXmIHU88Qw6XUhGTsKFLsRT1rsN25+6KZG
kH2gnnZUXK1+NSGbiNwlbrgpNHP30JjLH9ewX867hhp24PJ0ke+nlzScBwCgrxsc
kmPXMyFrbbPYMaFO5MfT/R0D/R3o5lhV7mbu2jxKUMfngJYv7uT+IZ8lyquKdIcX
kvwKKqmdPgSJQ9RhJeUYgAlKcZbQst7g2g+XktuotxwNdUdyTGKJA1ieZK7l89U/
zNvQuCnZ9vSzirKydpRVd+ReMupVYooC12GYOl9gLCJg1WQXYdjoKaKF7u1PUsRp
We3XA/9YRNq7alUTRTiS0LY1RfaQohprsLsF+pY+ZkB3A72CZWyWoxQG0uHL3ivq
mGlGYKriKTed4DBRp2ZREsGwbWAknh/wP4Is42qH1RzWRB7xnQsrxYuPFSr4c35D
AP9oFk2O4povTJ9Ay0QEnNRgncIoSuhEXQ0GRLETosmozqBOkLQ7TWFyYyBQcnVk
J2hvbW1lYXV4IChDT0RFIFNJR05JTkcgS0VZKSA8bXBydWRob21AYXBhY2hlLm9y
Zz6IYAQTEQIAIAUCRTf9zQIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEPeU
CvQRoa6ckGAAn131QtlLKvPdUh9NWYwgAsvN8FuSAJ9+8PTwxc4G4NhyNhYV0TcI
2kuANrkCDQRFN/3gEAgAmyDZTIcdHNN76dLsEA9tj+chVf2iDBFisrpmYMV4CM0R
tUD6GYhUDekKWaAs9PnTnqe+9b30NIEmORY6XktWD08GFwwp5loxlLuQlK66I29u
y1dS6J6HdxcFWJlg4v1AnKdHexUSHUbxNrZQtU+N3kAMhsopZhV3QwSK6djMb2Lo
SsNaSmpS+3L9siP8XwkxsPixOfXDTbKtFvb6p0idvetKPrulJnX+zJGupYa4KpkE
G7CpiWgcSFlGU/AVv4xfIqFUX3EwoQefIX/Nw+mlz2fZD0GCfosgLlA2x3gol2ks
77SgzzgH9acNF7xUoJTXHRZdz3Ue2CU2YSvCVBwV9wAFEQf+IXKZVdyjp+vAXSD2
lZHDzRlcI97dnAlsQYVmQOdDJf+haC8KBvZwSEdsCB4Ng6P1aX0xDh2gXxAUzEzJ
sjw4u7QvjKsx44SpC3wXsbJJdzwkM9nyneWul3DyyJ03YB0ReIuP/N5PZHLAKSIG
/n29AK16TJI+ePJtBfMhsjmaHvTjcEHALhG5eN1AtmCKMX60lSu9KYJK01gaiWgb
0lo9MyH4S7TqQHOqSUxF20Q/0fsN3ckkkelVy72vfB3lSbzQyZLrVCwqg10rjxQg
yjHi+tXM8R/gJaP5zRf5v1X0/kjAI2zo99l7eox4mgdfvpOojSBYJMn+097UVHW+
n0/ldohJBBgRAgAJBQJFN/3gAhsMAAoJEPeUCvQRoa6cu8oAoKzP/7i+YnyHHIpW
bZySWmV5ruNBAKCRPW44mWffxSsJ6oUeUSzvbsCwew==
=XKWe

**Comment by lorenzoPrimi** [comment]
Implemented in 2.0
