### ISSUE TITLE
The link color should be lighter

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#194]
In the onboarding screen (and I assume any other place where we use markdown), the color of links is a bit too dark to be readable.

See attached screenshot:
![screenshot 2018-12-11 at 13 22 11](https://user-images.githubusercontent.com/424620/49802060-28e15d00-fd4c-11e8-9428-5f1790a26601.png)

cc @elioqoshi @lorenzoPrimi

**Comment by lorenzoPrimi** [comment]
There is no such option in the library we are using at the moment, this link is not readable due to the background color.

PS. "e.g" is not a link, maybe @agrabeli you wanna change that string?

**Comment by hellais** [comment]
I see. Maybe we can make it slightly better by changing the background color? @elioqoshi what do you think?

**Comment by elioqoshi** [comment]
The problem with that is that if we change the background color, there will be lack of contrast with the regular text color. White and Link Dark Blue don't go well together as they are on opposite ends of the spectrum so there is not a perfect color which works for both of them (let alone be WCAG compliant). Could we somehow use another component or a workaround to have that link in normal text color (white) but just underlined?

**Comment by lorenzoPrimi** [comment]
First thing we should change that e.g from the copy to avoid being highlighted @agrabeli 
About the link color issue, unfortunately this library doesn't support link styling, just opened a ticket:
https://github.com/chriscdn/RHMarkdownLabel/issues/3

**Comment by elioqoshi** [comment]
We should definitely change that if only this shade of blue is the sole option.

**Comment by elioqoshi** [comment]
@lorenzoPrimi Could you please give context for us who do not understand what that commit means? :)

**Comment by lorenzoPrimi** [comment]
I simply implemented what has been said in https://github.com/chriscdn/RHMarkdownLabel/issues/3
