### ISSUE TITLE
Upload failures are not consistent

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#205]
While looking at `Containers/Data/Application/996BAE6A-EA41-407A-BA9F-09EF099515D7/Documents/OONIProbe.db` I found some inconsistencies in the database.

See:
```
sqlite> select is_upload_failed, upload_failure_msg, is_uploaded FROM Measurement;
0|parallel_operation_error|0
0|parallel_operation_error|0
0|parallel_operation_error|0
0|parallel_operation_error|0
0|parallel_operation_error|0
```

Every measurement has the `parallel_operation_error`, even in cases in which the measurement is actually uploaded. @lorenzoPrimi says this is due to filesystem reporting being switched on.

The other problem is that `is_upload_failed` is set to `false`, yet there is a non-empty `upload_failure_msg` in the second column. The code that handles trapping the upload failure should also set `is_upload_failed` to `true`.
https://github.com/ooni/probe-ios/blob/dev/ooniprobe/TestClasses/MKNetworkTest.mm#L172

The reason to track this separately inside of `is_upload_failed` (and not just use `is_uploaded`) is so that we can distinguish between a failure to upload due to bad network conditions vs the user having opted out of measurement uploading.

**Comment by lorenzoPrimi** [comment]
closed by https://github.com/ooni/probe-ios/commit/859e13e384a4ab0708bb1c53bc162a43c489ccde
