### ISSUE TITLE
Onboarding quiz transition artifact

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#208]
When you go through the onboarding quiz and get the answer wrong, there is an artifact when transitioning from the red X cross into the grey "You got it wrong" section showing the underlying question.

I suspect this has something to do with the "You got it wrong" grey box being enabled while the quiz question is still underneath.

A similar thing happens when you get the answer correct, for a fraction of a second you see the question 1 before seeing question 2.

Is there a way to clean these transitions up a bit?

**Comment by elioqoshi** [comment]
@lorenzoPrimi Should this go into 2.0.1? Are we doing another Milestone for that?

**Comment by lorenzoPrimi** [comment]
sure
