### ISSUE TITLE
The string country in the details page is not translated

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#210]
See screenshots:

![iphone 8 plus-04speedtest](https://user-images.githubusercontent.com/424620/50756702-def38480-12c1-11e9-8a77-7dc575fe1d14.png)

![iphone 8 plus-04speedtest](https://user-images.githubusercontent.com/424620/50756715-ea46b000-12c1-11e9-9c67-d1de29f3c987.png)

![iphone 8 plus-04speedtest](https://user-images.githubusercontent.com/424620/50756718-f0d52780-12c1-11e9-97a4-e754271bc2ff.png)

**Comment by lorenzoPrimi** [comment]
Fixed. I'm more concerned about the labels not be aligned anymore ...
