### ISSUE TITLE
Crash in nlohmann::detail::type_error

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#224]
This affects 6 users and is number `#60` on fabric.

Backtrace of error:

```
Fatal Exception: nlohmann::detail::type_error: [json.exception.type_error.316] invalid UTF-8 byte at index 32764: 0x2E
```

This is perhaps mk related.

cc @bassosimone

**Comment by bassosimone** [comment]
This is most likely an instance of https://github.com/measurement-kit/measurement-kit/issues/1823, fixed in MK v0.10.4. Let's close this and see whether there's a relapse.
