### ISSUE TITLE
Better testing for iOS app

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#233]
The iOS app currently has some very basic end to end tests (I would call this more of a smoke test), see: https://github.com/ooni/probe-ios/issues/121.

It would be great if we started to have:

1. More thorough end to end tests
2. Some extensive unittests (https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/04-writing_tests.html)

Related to: https://github.com/ooni/probe-android/issues/186 & https://github.com/ooni/probe-ios/issues/44

**Comment by bassosimone** [comment]
Either this or #121 seems a duplicate. Maybe we can keep just one of them?

**Comment by lorenzoPrimi** [comment]
Closed #121 as much of the work described there is done (screenshots automatically)
