### ISSUE TITLE
`input` has whole test-list instead of single URL

### ISSUE THREAD

**Issue by darkk** [ooni/probe-ios#234]
## Expected Behavior

The report has several measurements, every measurement has URL in `input` field.

## Actual Behavior

The submitted report has single measurement, with test-list stored in `input` field:

[`20190204T124107Z-RU-AS15378-web_connectivity-20190204T124110Z_AS15378_RT1Rk1iDo6e0Ly1hrlLGADyXQpk8gG72z6QIcZScSEAXiO29C2-0.2.0-probe.json`](https://github.com/ooni/probe-ios/files/2832580/20190204T124107Z-RU-AS15378-web_connectivity-20190204T124110Z_AS15378_RT1Rk1iDo6e0Ly1hrlLGADyXQpk8gG72z6QIcZScSEAXiO29C2-0.2.0-probe.json.txt).

## Steps to Reproduce the Problem

Unknown. I have no iOS device, the report have reached the pipeline and triggered a bug in it.

## Specifications

  - Version: software_version: 2.0.1-alpha.1, engine_version: 0.9.2
  - Platform: ooniprobe-ios
  - Subsystem: TBD

**Comment by darkk** [comment]
There are alike pathological cases coming from `ooniprobe` `2.1.0`, `2.2.0` and `2.3.0`, but those cases could be caused by some user error:

2.1.0:
- https://api.ooni.io/api/v1/measurement/temp-id-166584058

2.2.0:
- https://api.ooni.io/api/v1/measurement/temp-id-86077704
- https://api.ooni.io/api/v1/measurement/temp-id-86077711
- https://api.ooni.io/api/v1/measurement/temp-id-86077926
- https://api.ooni.io/api/v1/measurement/temp-id-86078033
- https://api.ooni.io/api/v1/measurement/temp-id-86078140
- https://api.ooni.io/api/v1/measurement/temp-id-86078246
- https://api.ooni.io/api/v1/measurement/temp-id-86078353
- https://api.ooni.io/api/v1/measurement/temp-id-86078567
- https://api.ooni.io/api/v1/measurement/temp-id-86078674
- https://api.ooni.io/api/v1/measurement/temp-id-86078888
- https://api.ooni.io/api/v1/measurement/temp-id-86078995
- https://api.ooni.io/api/v1/measurement/temp-id-86081292
- https://api.ooni.io/api/v1/measurement/temp-id-125992246

2.3.0:
- https://api.ooni.io/api/v1/measurement/temp-id-172762335
- https://api.ooni.io/api/v1/measurement/temp-id-172770501
- https://api.ooni.io/api/v1/measurement/temp-id-172771084

I've not found any other cases of alike malformed `input` field coming from iOS or Android.

**Comment by lorenzoPrimi** [comment]
@darkk I believe these measurements don't come from the iOS app as the `"software_name": "ooniprobe"` doesn't belong to the iOS app. I use `ooniprobe-ios`

**Comment by hellais** [comment]
@lorenzoPrimi for the ones listed in: https://github.com/ooni/probe-ios/issues/234#issuecomment-460724836 you are right,  those are from probe-legacy.

The ones listed in: https://github.com/ooni/probe-ios/issues/234#issue-406824382 are from probe-ios (`* Version: software_version: 2.0.1-alpha.1, engine_version: 0.9.2`, `* Platform: ooniprobe-ios`)

**Comment by lorenzoPrimi** [comment]
@darkk what this has to do with probe-ios? I guess is more mk related @bassosimone 
`2.0.1-alpha.1` is the app used with the new mkall.

**Comment by bassosimone** [comment]
@lorenzoPrimi, in the measurement cited by @hellais, the engine version is 0.9.2. That is, to the very least, this is not related to me rolling out MK v0.9.3 and mkall-ios v0.3.10.

It could also be related to MK on a more fundamental level. The question to be asked is probably whether in MK there is code capable of dealing with test lists. And, also, what happens if you feed MK with an entire test list. My best guess is that what happens is likely what we see here, but I’d like to double check.

What I am quite sure of, however, is that there is no code capable of reassembling a test list, given correct input. This leads me to think that perhaps MK is provided as input such test list.

**Comment by lorenzoPrimi** [comment]
This an example of a part of the `input` string : `http:\/\/comingoutspb.ru\/en\/en-home,LGBT,LGBT,2014-04-15,citizenlab`
We don't have test lists in the app since 1.x, we have url, country code and category, no date or "citizenlab" as you can see here `https://orchestrate.ooni.io/api/v1/test-list/urls`

so I really can't understand where these come from

**Comment by bassosimone** [comment]
Could be. Maybe we should use an annotation when a test is a OONI Run test?

(We can also guess from the URLs in many cases, but possibly not here)

**Comment by darkk** [comment]
> @darkk do you have more reports maybe from versions more stable than an 2.0.1-alpha.1

Nope, so far it was just the single one report with that pattern. I believe, it could be some sort of user error, indeed.

I'm unsure if we should do blocking (or non-blocking) validation in the app for alike cases. As far as I understand, the user got reasonably "instant" feedback on the mistake from MK failing the measurement of this erratic "URL". UX may be improved, but I'm unsure if it's worth improving :)

**Comment by lorenzoPrimi** [comment]
What did we decide from this thread? Should we add an annotation to links ran from OONI Run?

**Comment by bassosimone** [comment]
Yes, please!

**Comment by hellais** [comment]
I would suggest doing two things here:
1. If we notice a URL in the list we are about to test which is longer than 2,083 character (this is maximum URL length size in IE) in OONI Run we should consider it to be malformed and show an error and not allow running it

2. Add an annotation for things that are run via OONI Run. Maybe it can be `"origin": "ooni-run"`
