### ISSUE TITLE
Make sure we allow users to see logs with a malformed JSON

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#242]
This is related to https://github.com/ooni/probe-android/issues/196. There we know that, when a JSON is malformed, we should _still_ allow a user to see the logs. That's possibly the case where the logs would be mostly useful. I'm not sure if the iOS app has this issue, tho, but I suggest to check whether that is the case and, if needed, fix the issue in the code, otherwise just close this issue.

**Comment by elioqoshi** [comment]
This is probably related to this: https://github.com/ooni/probe/issues/850

**Comment by bassosimone** [comment]
Yes, I'd say let's just keep the above open.
