### ISSUE TITLE
Performance not WAI with app in background

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#249]
## Expected Behavior

When I start a performance test and lock my phone, I expect both ndt and dash to complete.

## Actual Behavior

Ndt completes and dash fails.

## Steps to Reproduce the Problem

  1. download OONI probe 2.0.4 from the App Store
  2. run a performance test
  3. lock the phone during the test
  4. check after some minutes whether it completed

## Specifications

  - Version: 2.0.4
  - Platform: iOS
  - Subsystem: unclear

**Comment by lorenzoPrimi** [comment]
@bassosimone can you also try with longer tests such as websites?
And try also test with multiple subtests (im or middle boxes)

**Comment by lorenzoPrimi** [comment]
Tried it and worked without problems. With "lock phone" you mean closing ooniprobe or shut down the screen?

**Comment by bassosimone** [comment]
Tests run using v2.1.0 (71):

1. start performance, lock the phone, wait for 5 minutes, unlock the phone. Status of the phone when I unlock it is the following:

![IMG_2296](https://user-images.githubusercontent.com/337298/59123132-d67ca400-895c-11e9-9f04-614d79006e73.JPG)

2. start performance, switch app, wait for 5 minutes, switch back. Status of the phone when I switch back:

![IMG_2298](https://user-images.githubusercontent.com/337298/59123152-e5fbed00-895c-11e9-8d90-c3ee89ff1fa9.JPG)

It's interesting to note the results of these two tests:

![IMG_2300](https://user-images.githubusercontent.com/337298/59123212-062bac00-895d-11e9-98e1-d579a0119806.JPG)

Maybe more tests later.

**Comment by bassosimone** [comment]
@lorenzoPrimi you also asked about IM and Websites. For IM, I have other kind of issues that I'll document separately, but it's definitely working as intended in background. For websites, this one also seems to be working as intended, event though also in this case I've found issues.

**Comment by bassosimone** [comment]
So, it seems all of this was caused by a massive problem between the keyboard and the chair:

![IMG_2302](https://user-images.githubusercontent.com/337298/59149141-4305aa80-8a12-11e9-8dc7-9b72f6613486.png)

With that global setting re-enabled, everything was WAI.
