### ISSUE TITLE
Web connectivy test: website categories show a different number of categories enabled

### ISSUE THREAD

**Issue by gusgustavo** [ooni/probe-ios#250]
## Expected Behavior

In "Websites categories to test", if you select one or more categories to test, it should change the switch button (on/off) and then show you the exact number of categories you selected.

## Actual Behavior

In "Websites categories to test", if you select one category and scroll down, the switch button will return to the previous status, and if you select and return to the previous screen, it will say that you selected more categories than you actually did. But the test will run correctly and after it, it will show you the right categories that you selected.

## Steps to Reproduce the Problem

  1. In OONI probe (iOS only), select Websites, tap card and touch the settings icon.
  2. Touch website categories to test.
  3. Select only the category that you want to test, for example, Culture.
  4. Return to the previous screen and it will show a different number of categories enabled.

## Specifications

  - Version: 2.0.5
  - Platform: iOS
  - Subsystem:

**Comment by lorenzoPrimi** [comment]
Thanks for the report, fixed
