### ISSUE TITLE
iPhone SE issues

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe-ios#254]
Test name cut
![Simulator Screen Shot - iPhone SE - 2019-03-29 at 11 29 04](https://user-images.githubusercontent.com/1616097/55219536-372d8900-5216-11e9-9b35-090fcaac1a06.png)

Test details cut
![Simulator Screen Shot - iPhone SE - 2019-03-29 at 11 29 06](https://user-images.githubusercontent.com/1616097/55219538-372d8900-5216-11e9-937e-4eacf34f95a3.png)

View not scrollable
![Simulator Screen Shot - iPhone SE - 2019-03-29 at 11 29 08](https://user-images.githubusercontent.com/1616097/55219539-37c61f80-5216-11e9-93e6-e7edd118947e.png)

**Comment by lorenzoPrimi** [comment]
Third one fixed https://github.com/ooni/probe-ios/commit/ef03d82d068316c1914e87315beffbd567ae15fa

**Comment by lorenzoPrimi** [comment]
Second one fixed

**Comment by lorenzoPrimi** [comment]
Nothing much we can do for the first one unless we want to make these rows multi lines.
This will also affect websites that will become multi line. Leaving last word to @elioqoshi 
![Simulator Screen Shot - iPhone SE - 2019-03-29 at 17 20 07](https://user-images.githubusercontent.com/1616097/55239038-e97d4480-5246-11e9-890a-89bef60478bd.png)

**Comment by elioqoshi** [comment]
@lorenzoPrimi sorry I missed this.

Can we have a preview how it would look like multi-line?

**Comment by lorenzoPrimi** [comment]
It's not so straightforward to make it, otherwise I would have pushed it in the branch.
Look the Android app (actually that one is limited to two rows) the other alternative is to make the row of automatic height based on how many lines we need

**Comment by lorenzoPrimi** [comment]
Closing it as the major 2/3 issues were resolved, handling the first one will create more problems than solutions
