### ISSUE TITLE
Issue when the user has no address configured on the Mail app

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/probe-ios#273]
When the user has no address configured on the Mail app there is no way send a mail in a native way, the default behaviour suggested by apple is to inform the user there are no accounts:
https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller

![Image from iOS](https://user-images.githubusercontent.com/1616097/57635256-72f69500-75af-11e9-8f18-89bab8c34497.jpg)

One solution could be to show a different message such as
“No email clients configured on your device, please send us an email to bugs@openobservatory.org from your email client” 
With two buttons: "Copy to clipboard", "cancel"

Or we could open a web page with a contact form, in this case we can also inject data such as app version and os version.

**Comment by holantonela** [comment]
@lorenzoPrimi how relevant/useful is the bug reporting if you don't have the app and the OS version? 

I see that moving between email clients could require an extra effort. So, the second option seems the most convenient both for users and for us. Let me know if you already have an UI for a message in a modal or if I should work on it.

**Comment by lorenzoPrimi** [comment]
I also think that if the user doesn't have the Mail app configured we should redirect them to a web form. I believe the majorities of iOS users have the Mail app coinfigured and there is no way to intercept an alternative client.
What is @hellais opinion on this?

**Comment by hellais** [comment]
Redirecting them to a web form though is a whole new feature that needs to be implemented.

It does create then the problem of how do we make this censorship resistant (places with issues may have ooni.torproject.org be blocked).

I think that if we can find a solution that works in all cases even if that means not getting app version info (we can request the user specifies this when composing the email in the copy) it's better than nothing.

Once we get an email from the user we can also follow up via email asking more information to troubleshoot the problem.

My proposal for a solution would be that when no email client is configured you show a modal saying:
> Please send an email to bugs@openobservatory.org with information on the app and iOS version. Tap copy to clipboard below to copy our email address.
[ cancel ] [ copy email address ]

**Comment by lorenzoPrimi** [comment]
@hellais so without the initial part "No email clients configured on your device, " ?

**Comment by lorenzoPrimi** [comment]
What's @agrabeli opinion on the copy here?
So I will submit it to transifex

**Comment by hellais** [comment]
> so without the initial part "No email clients configured on your device, " ?

I would not put that there as I don't think the user really should act upon it (it's not like a user is going to switch to using the Mail app client or configure an email on their phone just to contact our support).

Since there is a viable workaround for it, we should tell them of the workaround and encourage them to use it.
