### ISSUE TITLE
QA: @bassosimone check-list for v2.1.0 (71)

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#283]
# App

- [x] verify that version numbers are reasonable
- [x] verify that settings are default

# Websites test

- [x] verify that settings are default
- [x] run the test in foreground without specifying any option
    - [x] check that the time is decreasing
- [x] run the test in foreground and then put the app in background
    - [x] make sure that the time is making progress
    - [ ] make sure that you receive a notification [XXX]
    - [x] make sure that the test performed work in background
- [x] run the test with just https://ooni.torproject.org/ and https://expired.badssl.com/
- [x] run the test with only some categories
    - [x] make sure you did only actually test these categories
- [ ] run the test with a very short test runtime [XXX]
- [ ] run the test without uploading measurements and then perform a background upload [XXX]
- [x] results analysis of all the above
    - [x] check that the summary shows some number blocked some accessible
    - [x] check that the blocked sites are displayed first
    - [x] check that the icons are displayed next to each measurement
    - [x] check that the data usage shows a sane number, ex 6.3MB up, 5.8MB down
    - [x] check that the total runtime shows a sane number, ex. 257s
    - [x] check specific measurements (at least one okay, one blocked)
        - [x] check that everything is displayed properly in this screen
        - [x] check that the runtime is sane ex 2.71s
        - [x] check that the data makes sense
        - [x] check that the logs make sense

# IM tests

- [x] verify that settings are default
- [x] run the test in foreground without specifying any option
    - [x] check that the time is decreasing
- [x] run the test in foreground and then put the app in background
    - [x] make sure that the time is making progress
    - [ ] make sure that you receive a notification [XXX]
    - [x] make sure that the test performed work in background
- [x] run just one of the tests and verify the others didn't
- [x] results analysis of all the above
    - [x] check that the total count on top matches
    - [x] check that the total counts on top match
    - [x] check that the data usage shows a sane number, ex 36KB up, 18KB down
    - [x] check that the total runtime shows a sane number, ex. 2.16s
    - [x] check specific measurements
        - [x] check that everything is displayed properly in this screen
        - [x] check that the runtime is sane ex 2.71s
        - [ ] check that the data makes sense [XXX]
        - [x] check that the logs make sense

# Middlebox test

- [x] verify that settings are default
- [x] run the test in foreground without specifying any option
    - [x] check that the time is decreasing
- [x] run the test in foreground and then put the app in background
    - [x] make sure that the time is making progress
    - [ ] make sure that you receive a notification [XXX]
    - [x] make sure that the test performed work in background
- [x] run just one of the tests and verify the others didn't
- [x] results analysis of all the above
    - [x] check that the data usage shows a sane number, ex 8KB up, 4KB down
    - [x] check that the total runtime shows a sane number, ex. 5s
    - [x] check specific measurements
        - [x] check that everything is displayed properly in this screen
        - [x] check that the runtime is sane ex 2.71s
        - [x] check that the data makes sense
        - [x] check that the logs make sense

# Performance test

- [x] verify that settings are default
- [x] run the test in foreground without specifying any option
    - [x] check that the time is decreasing
- [x] run the test in foreground and then put the app in background
    - [ ] make sure that the time is making progress [XXX]
    - [ ] make sure that you receive a notification [XXX]
    - [ ] make sure that the test performed work in background [XXX]
- [x] run just one of the tests and verify the others didn't
- [x] results analysis of all the above
    - [x] check that you see upload, download and video speed in the summary
    - [x] check individual results and see whether they make sense
    - [x] check that the data usage shows a sane number, ex 22MB up, 104MB down
    - [x] check that the total runtime shows a sane number, ex. 54s
    - [x] check specific measurements
        - [x] check that everything is displayed properly in this screen
        - [x] check that the runtime is sane ex 30s
        - [x] check that the data makes sense
        - [x] check that the logs make sense

# Results visualization

- [x] try to adjust the filter and validate that only the filtered results appear
- [x] tap the result row
    - [x] check that the last run test is highlighted
    - [x] check that the date & time of the test are correct and displayed in the timezone of the phone
    - [x] check that the country & network are resolved properly
- [x] tap the measurement row
    - [x] check that the country & network are resolved properly
    - [x] check that it’s possible to view the log
    - [x] check that it’s possible to view data
    - [x] check that the report_id is not null, unless publish result is disabled
    - [x] check that the test_start_time in the measurement is using GMT

# Settings

- [x] notifications
    - [x] try to enable notifications and ensure that it asks you to enable it in the system settings (assumes you have disabled it in the system settings)
- [x] sharing
    - [x] disable publish results. Run a test and verify that the result does not include your report_id
    - [x] disable “include network info”, “include country code”, “include my IP address”. Run a test and validate that the expected information appears in the results
- [x] advanced
    - [x] enable debug logs and run a test. Check that the logs are at debug level verbosity.
- [x] About
    - [x] check that all the links in the about page work as expected

# OONI Run

- [x] Check that tappng tapping on the following web_connectivity OONI Run link works as expected:
    - [x] no inputs: https://run.ooni.io/nettest?tn=web_connectivity&mv=2.0.0 
    - [ ] empty inputs: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%5D%7D&mv=2.0.0 [XXX]
    - [x] partial input: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2F%22%5D%7D&mv=2.0.0
    - [x] valid URLs: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Fwww.google.it%22%2C%22https%3A%2F%2Frun.ooni.io%2F%22%5D%7D&mv=2.0.0 
     - [ ] WC Crash: https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Fwww.google.it%22%2C%22https%3A%2F%2Frun.ooni.io&mv=2.0.0 [XXX]
- [x] check it’s possible to run NDT via OONI Run: https://run.ooni.io/nettest?tn=ndt&mv=2.0.0
- [x] check it’s possible to run Dash https://run.ooni.io/nettest?tn=dash&mv=2.0.0
- [x] check it’s possible to run HIRL https://run.ooni.io/nettest?tn=http_invalid_request_line&mv=2.0.0
- [x] check it’s possible to run HHFM https://run.ooni.io/nettest?tn=http_header_field_manipulation&mv=2.0.0
- [x] Check that the minimum version is being verified Min version error https://run.ooni.io/nettest?tn=ndt&mv=15.0.0
- [x] check that an error is shown when a non-existent Test name is selected https://run.ooni.io/nettest?tn=fake_test_name&mv=2.0.0

**Comment by bassosimone** [comment]
# Issues found

I'll open specific issues later, for now I'd like to document what has not working correctly for me while performing QA testing of this release candidate:

1. never received a completion notification for the websites test

2. the websites runtime is an upper bound (we already know that, but it's confusing)

3. background upload is very slow with many measurements to upload (see https://github.com/ooni/probe/issues/861)

4. the completion notification for IM says `(null) completed`

5. data for all IM tests is blank

6. the completion notification for middlebox says `(null) completed`

7. it's impossible for me running performance in the background; DASH specifically seems to be stuck and resumes - after several minutes - from where it stopped when you put the app in background

**Comment by bassosimone** [comment]
# Follow up

It turns out #249 (i.e. items 1 and 7 in the above list) was PBKAC.

Created issue #284 for items 4 and 6.

No immediate action required for items 2 and 3. They're annoying issues related to MK that we cannot fix in a couple of days but we'll definitely try to improve upon in subsequent releases.

Unclear what to do with item 5: it seems this didn't occur in subsequent tests ¯\_(ツ)_/¯.

**Comment by bassosimone** [comment]
I think I can call this round of QA complete. I believe we should fix #284 before releasing, tho.

**Comment by bassosimone** [comment]
Actually, it occurred to me that I skipped part of the original check list. Reopening.

**Comment by bassosimone** [comment]
@lorenzoPrimi finished testing. Please, tell me what is the desired OONI run behaviour in case of empty input and in the "WC crash" case, because I don't know what to check for.

Also, it seems I've been able to obtain a case where a measurement cannot be loaded. It happened by chance, tho, and I don't know very well how to further investigate.

**Comment by lorenzoPrimi** [comment]
Ignore WC crash, it was an old scenario where the app should have crashed and it has been fixed.

**Comment by bassosimone** [comment]
What is the desired behaviour in case of empty input?

**Comment by lorenzoPrimi** [comment]
Exactly. Ignores non valid inputs

**Comment by bassosimone** [comment]
OK, thanks!
