### ISSUE TITLE
Measurements not reliably loaded

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-ios#286]
## Expected Behavior

We always load measurements

## Actual Behavior

Sometimes you load a measurement and it's blank

## Steps to Reproduce the Problem

  1. run measurements
  2. repeatedly tap to measurements until there is a blank one
 
(It may be useful to do this with the phone attached to a mac computer, so that it's easier to catch possible errors when they occur; otherwise, it's kinda a shot in the dark.)

## Specifications

  - Version: v2.1.0 (71)
  - Platform: iOS

**Comment by lorenzoPrimi** [comment]
Clone of https://github.com/ooni/probe/issues/865
