### ISSUE TITLE
Copy explorer URL should not be an option when the measurement is not uploaded

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#306]
In the unreleased beta (2.2.0-beta.3) when you disable automatic measurement upload and go into the measurement and do "Copy Explorer URL" the URL is copied even if the measurement is not uploaded and the copied URL is `https://explorer.ooni.io/measurement/(null)`.

Instead this option should be available as the measurement has not been uploaded.

I have tested this on iOS, but it may also be present on Android.

**Comment by lorenzoPrimi** [comment]
It is also present in android. So should that option be enabled only if I have a non-null measurement id?

**Comment by lorenzoPrimi** [comment]
What if instead of removing the button, we show a popup saying "This measurement has not been uploaded to OONI Explorer" ?

**Comment by hellais** [comment]
> So should that option be enabled only if I have a non-null measurement id?

I think what you want to be checking is if the measurement has been uploaded. If it has not been uploaded it's not possible to share an explorer URL.

> What if instead of removing the button, we show a popup saying "This measurement has not been uploaded to OONI Explorer" ?

Ideally we would just not show the button as there is no point in having them click on it since the measurement is not uploaded.
