### ISSUE TITLE
Abnormal web connectivity results burried

### ISSUE THREAD

**Issue by willscott** [ooni/probe-ios#78]
There doesn't seem to be a particular ordering to the test results for web connectivity. Maybe collapse into counts of "20 successful", "4 failed" rather than a list of domains?  The only ones with errors showed up below the first scroll line and weren't immediately obvious.

**Comment by bassosimone** [comment]
I seem to recall there was a discussion where by default only interesting results were shown and one may then decide to show everything. Isn't it, @hellais?

**Comment by bassosimone** [comment]
Xref: TheTorProject/ooniprobe-android#59

**Comment by bassosimone** [comment]
Yeah, I totally believe this would be useful. I think I'll propose this as a topic for [today's hackathon on OONI that will be hosted by Torino Hacknights](http://torino.hacknight.it/2017/05/30/ooni/).

**Comment by lorenzoPrimi** [comment]
implemented here https://github.com/ooni/probe-ios/commit/50634c137a47ef36c8a9260c8358362d75fb1a70
