### ISSUE TITLE
Detect when there is no connectivity

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#82]
We should detect when the user is not connected to wifi or 3g and if so disable running network measurements (or show an error message when they try to start a test).

**Comment by anadahz** [comment]
I guess it makes sense to also detect if a user is connected to a USB, Bluetooth or LAN network connection with internet connectivity.

**Comment by bassosimone** [comment]
I think this is now done as part of orchestration, right, @lorenzoPrimi?

**Comment by lorenzoPrimi** [comment]
There is already a class that does the network detection. So it's gonna be an easy implementation

**Comment by lorenzoPrimi** [comment]
The new app will not run test if no connectivity is detected
